name: Deploy ke Heroku

on:
  workflow_dispatch:
  push:
    branches:
      - master  # atau ganti dengan nama branch kamu

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: curl https://cli-assets.heroku.com/install.sh | sh

      - name: Login ke Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: echo "$HEROKU_API_KEY" | heroku auth:token

      - name: Set Heroku stack ke container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku stack:set container --app herta

      - name: Heroku Container Login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Push Docker ke Heroku
        run: heroku container:push web --app herta
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Rilis ke Heroku
        run: heroku container:release web --app herta
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
